name: My first CI/CD

on:
 push:
  branches:
   - main

jobs:
  sys_info-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository

      - name: Give Execute Permission
        run: chmod +x sys_info.sh

      - name: Run Bash Script
        run: ./sys_info.sh
